---
version: "3.0"

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - $HOME/homeservices/heimdall:/config
    ports:
      - 8081:80
      - 443:443
    restart: unless-stopped
