---
version: "3.0"

services:
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - $HOME/homeservices/transmission/data:/config
      - $HOME/homeservices/transmission/downloads:/downloads
      - $HOME/homeservices/transmission/watch:/watch
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
      - TRANSMISSION_WEB_HOME=/flood-for-transmission/
    restart: unless-stopped
 
