- name: check if nodes are ready
  hosts: all
  
  tasks:
    - name: ping nodes
      ping:

    - debug:
        msg: success! start cluster setup - `ansible-playbook -i .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory setup.yaml`
