# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

# centos image is required while working with libvirt
IMAGE = "generic/centos7"
CTL_CPU   = 4		# minimal is 2
CTL_MEM   = 4096	# minimal is 2048
WRK_NODES = 1	
WRK_CPU   = 4
WRK_MEM   = 4096

Vagrant.configure("2") do |config|

  config.vm.define "master-node" do |sub|
    # make sure you specified correctly your bridge and dev. type `ip a` to check
    sub.vm.network "private_network", ip: "172.16.0.2", "bridge": "enp2s0", "dev": "enp2s0"
    config.vm.network "forwarded_port", guest: 2222, host: 2222
    sub.vm.box = IMAGE
    sub.vm.hostname = "master-node"
    sub.vm.provider :libvirt do |libvirt|
      libvirt.nested = true
      libvirt.cpus = CTL_CPU 
      libvirt.memory = CTL_MEM
    end
  end

  (1..WRK_NODES).each do |i|
    config.vm.define "node-#{i}" do |sub|
    # same story here
    sub.vm.network "private_network", ip: "172.16.0.#{i+2}", "bridge": "enp2s0", "dev": "enp2s0"
    config.vm.network "forwarded_port", guest: 2222, host: 2222
    sub.vm.box = IMAGE
    sub.vm.hostname = "node-#{i}"
    sub.vm.provider :libvirt do |libvirt|
      libvirt.nested = true
      libvirt.cpus = WRK_CPU
      libvirt.memory = WRK_MEM
    end
  end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.groups = {
      "master" => ["master-node"],
      "node" => ["node-1", "node-2"]
    }
    ansible.playbook = "ping.yaml"
  end

end 
