# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

IMAGE = "generic/centos7"
NODES = 1

Vagrant.configure("2") do |config|

  config.vm.define "master" do |sub|
    sub.vm.network "public_network", ip: "192.168.31.221"
    sub.vm.box = IMAGE
    sub.vm.host_name = "master"
    sub.vm.provider "virtualbox" do |v|
      v.linked_clone = true
      v.name = "vagrant-master"
    end
  end

  (1..NODES).each do |i|
    config.vm.define "node#{i}" do |sub|
    sub.vm.box = IMAGE
    sub.vm.host_name = "node#{i}"
    sub.vm.network "public_network", ip: "192.168.31.22#{i+1}"
      sub.vm.provider "virtualbox" do |v|
        v.linked_clone = true
        v.name = "vagrant-node#{i}"
      end
    end 
  end 

end
